#!/bin/bash

# backup gitconfig
cp -f /home/liwei/.gitconfig /home/liwei/dotfiles/_gitconfig
echo 'backing up .gitconfig ...'


# backup vimperator
cp -f /home/liwei/.vimperatorrc /home/liwei/dotfiles/_vimperatorrc
echo 'backing up .vimperatorrc ...'
rm -rf _vimperator
mkdir _vimperator
mkdir _vimperator/plugin
mkdir _vimperator/colors
cp -rf /home/liwei/.vimperator/plugin _vimperator/
cp -rf /home/liwei/.vimperator/colors _vimperator/
echo 'backing up .vimperator ...'


# backup muttatorrc
cp -f /home/liwei/.muttatorrc /home/liwei/dotfiles/_muttatorrc
echo 'backing up .muttatorrc ...'


# backup awesome
rm -rf _config/awesome
cp -rf /home/liwei/.config/awesome _config/
echo 'backing up .config/awesome ...'
