#!/bin/bash

# backup gitconfig
cp -f /home/liwei/.gitconfig /home/liwei/dotfiles/gitconfig
echo 'backing up .gitconfig ...'


# backup vimperator
cp -f /home/liwei/.vimperatorrc /home/liwei/dotfiles/vimperatorrc
cp -rf /home/liwei/.vimperator /home/liwei/dotfiles/vimperator
echo 'backing up .vimperator ...'


# backup awesome
cp -rf /home/liwei/.config/awesome /home/liwei/dotfiles/awesome
echo 'backing up .config/awesome ...'
